packages:
  - packages/*

allowBuilds:
  esbuild: true

catalog:
  '@eslint/js': '10.0.1'
  '@tsconfig/strictest': '2.0.8'
  '@types/node': '25.9.3'
  chess.js: '1.4.0'
  eslint: '10.4.1'
  eslint-config-prettier: '10.1.8'
  eslint-formatter-pretty: '7.1.0'
  eslint-plugin-prettier: '5.5.6'
  eslint-plugin-simple-import-sort: '13.0.0'
  globals: '17.6.0'
  prettier: '3.8.4'
  prettier-plugin-packagejson: '3.0.2'
  prettier-plugin-sh: '0.18.1'
  tsx: '4.22.4'
  typescript: '6.0.3'
  typescript-eslint: '8.61.0'
  zx: '8.8.5'

minimumReleaseAgeExclude:
  - '@types/node@25.9.3'
