packages:
  - packages/*

allowBuilds:
  esbuild: true

catalog:
  '@eslint/js': '9.39.4'
  '@inquirer/select': '5.2.1'
  '@node-cli/logger': '1.3.8'
  '@tsconfig/strictest': '2.0.8'
  '@types/node': '25.9.3'
  '@types/react': '19.2.17'
  chess.js: '1.4.0'
  eslint: '9.39.4'
  eslint-config-prettier: '10.1.8'
  eslint-formatter-pretty: '7.1.0'
  eslint-plugin-import: '2.32.0'
  eslint-plugin-prettier: '5.5.6'
  eslint-plugin-react: '7.37.5'
  eslint-plugin-react-hooks: '7.1.1'
  eslint-plugin-simple-import-sort: '13.0.0'
  globals: '17.6.0'
  ink: '7.0.5'
  prettier: '3.8.4'
  prettier-plugin-packagejson: '3.0.2'
  prettier-plugin-sh: '0.18.1'
  react: '19.2.7'
  react-devtools-core: '7.0.1'
  tsx: '4.22.4'
  typescript: '6.0.3'
  typescript-eslint: '8.61.0'
  zx: '8.8.5'

minimumReleaseAgeExclude:
  - '@types/node@25.9.3'
