import type { PieceSymbol } from 'chess.js'

export type PieceSprite = {
  pixels: readonly (readonly boolean[])[]
}

const filledPixel = '██'
const transparentPixel = '..'
export const pieceSpriteHeight = 8
export const pieceSpriteWidth = 8
const pixelWidth = 2

const pieceSpriteSources = {
  b: `
................
......████......
....████........
....████████....
......████......
......████......
....████████....
..████████████..
`,
  k: `
................
......████......
....████████....
......████......
..████████████..
..████████████..
....████████....
..████████████..
`,
  n: `
................
......████......
....████████....
..██████████....
..██████████....
......██████....
....████████....
..████████████..
`,
  p: `
................
......████......
......████......
....████████....
......████......
......████......
....████████....
..████████████..
`,
  q: `
................
......████......
..██..████..██..
..████████████..
....████████....
......████......
....████████....
..████████████..
`,
  r: `
................
..██..████..██..
..████████████..
....████████....
....████████....
....████████....
..████████████..
..████████████..
`,
} as const satisfies Record<PieceSymbol, string>

export const pieceSprites = Object.fromEntries(
  Object.entries(pieceSpriteSources).map(([piece, source]) => [piece, parsePieceSprite(source)]),
) as Record<PieceSymbol, PieceSprite>

function parsePieceSprite(source: string): PieceSprite {
  const rows = source.trim().split('\n')

  if (rows.length !== pieceSpriteHeight) {
    throw new Error(`Expected piece sprite to have ${pieceSpriteHeight} rows.`)
  }

  const pixels = rows.map(row => parsePieceSpriteRow(row))

  return { pixels }
}

function parsePieceSpriteRow(row: string): readonly boolean[] {
  const expectedWidth = pieceSpriteWidth * pixelWidth

  if (row.length !== expectedWidth) {
    throw new Error(`Expected piece sprite row to be ${expectedWidth} characters wide.`)
  }

  const pixels: boolean[] = []

  for (let index = 0; index < row.length; index += pixelWidth) {
    const chunk = row.slice(index, index + pixelWidth)

    if (chunk === filledPixel) {
      pixels.push(true)
    } else if (chunk === transparentPixel) {
      pixels.push(false)
    } else {
      throw new Error(`Unknown piece sprite pixel "${chunk}".`)
    }
  }

  return pixels
}
